2018-03-19T17:26:10.613Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'undefined' in collection with ID 'Asset:org.lockerney.main.UserServicePair' does not exist)
    at /home/shyam8/.nvm/versions/node/v9.8.0/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-03-19T17:26:10.614Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'undefined' in collection with ID 'Asset:org.lockerney.main.UserServicePair' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'undefined' in collection with ID 'Asset:org.lockerney.main.UserServicePair' does not exist)\n    at channel.queryByChaincode.then.catch (/home/shyam8/.nvm/versions/node/v9.8.0/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-03-19T17:27:38.461Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'undefined' in collection with ID 'Asset:org.lockerney.main.UserServicePair' does not exist)
    at /home/shyam8/.nvm/versions/node/v9.8.0/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-03-19T17:27:38.461Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'undefined' in collection with ID 'Asset:org.lockerney.main.UserServicePair' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'undefined' in collection with ID 'Asset:org.lockerney.main.UserServicePair' does not exist)\n    at channel.queryByChaincode.then.catch (/home/shyam8/.nvm/versions/node/v9.8.0/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-03-20T06:11:47.101Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: Peer has rejected transaction 'c7e5d5e5e88153797799065dbaddf939217b4ba3c77414a61e4e2ec76e546122' with code MVCC_READ_CONFLICT","stack":"Error: Error trying invoke business network. Error: Peer has rejected transaction 'c7e5d5e5e88153797799065dbaddf939217b4ba3c77414a61e4e2ec76e546122' with code MVCC_READ_CONFLICT\n    at _initializeChannel.then.then.then.then.catch (/home/shyam8/.nvm/versions/node/v9.8.0/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:118:7)"}$
2018-03-20T06:13:45.467Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '12414' as the object already exists)
    at /home/shyam8/.nvm/versions/node/v9.8.0/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-03-20T06:13:45.467Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '12414' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '12414' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/shyam8/.nvm/versions/node/v9.8.0/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-03-20T09:21:52.038Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '12416' as the object already exists)
    at /home/shyam8/.nvm/versions/node/v9.8.0/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-03-20T09:21:52.038Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '12416' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '12416' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/shyam8/.nvm/versions/node/v9.8.0/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
